import numpy as np
from ..configs.message_config import ERROR_MESSAGES as ERROR_MESSAGES, WARNING_MESSAGES as WARNING_MESSAGES
from ..enums.color_modes import ColorModes as ColorModes
from .color_utils import enhance_color as enhance_color, ensure_rgb_mode as ensure_rgb_mode, get_contrast_color as get_contrast_color, rgb_to_gray as rgb_to_gray
from .font_util import calculate_char_size as calculate_char_size
from .progress_bar_utils import show_project_status_progress as show_project_status_progress
from PIL import Image
from _typeshed import Incomplete
from typing import Any, Callable

logger: Incomplete

def calculate_resized_dimensions(limit_size: list[int] | None, image: Image.Image, frame_index: int | None = None, is_show: bool = True, font_size: int | None = None) -> tuple[int, int]: ...
def resize_image_for_chars(limit_size: list[int] | None, image: Image.Image, frame_index: int | None = None, is_show: bool = True, font_size: int | None = None) -> Image.Image: ...
def pixel_to_char(pixel: int | float | tuple[int, ...] | tuple[tuple[int, ...], ...] | None, char_set: str, char_count: int) -> str: ...
def pixel_to_char_gpu(pixels_gpu: Any, char_count: int, torch: Any, device: Any) -> Any: ...
def image_to_char_text(resized_image: Image.Image, use_gpu: bool, torch: Any, device: Any, char_set: str, char_count: int, should_stop: Callable[[], bool] | None = None) -> str: ...
def create_char_image(resized_image: Image.Image, use_gpu: bool, char_set: str, char_count: int, color_mode: ColorModes, font: Any, torch: Any, device: Any, frame_index: int | None = None, position: int = 0, should_stop: Callable[[], bool] | None = None) -> tuple[Image.Image, str]: ...
def process_image_gpu(resized_frame: Image.Image, draw: Any, char_lines: list[str], width: int, height: int, char_width: int, char_height: int, torch: Any, device: Any, char_set: str, char_count: int, color_mode: ColorModes, font: Any, frame_index: int | None, position: int = 0, should_stop: Callable[[], bool] | None = None) -> None: ...
def process_image_cpu(resized_image: Image.Image, draw: Any, char_lines: list[str], width: int, height: int, char_width: int, char_height: int, font: Any, char_set: str, char_count: int, color_mode: ColorModes, frame_index: int | None, position: int = 0, should_stop: Callable[[], bool] | None = None) -> None: ...
