from PIL import Image as Image
from typing import Any

def rgb_to_gray(r: int, g: int, b: int) -> int: ...
def enhance_color(r: int | float | Any, g: int | float | Any, b: int | float | Any, saturation_factor: float = 1.5, brightness_factor: float = 1.2, torch: Any | None = None) -> tuple[int, int, int] | tuple[Any, Any, Any]: ...
def get_contrast_color(r: int, g: int, b: int) -> tuple[int, int, int]: ...
def ensure_rgb_mode(image: Image.Image) -> Image.Image: ...
