import threading
from _typeshed import Incomplete
from pathlib import Path
from typing import Any, Callable

from ..enums import ColorModes as ColorModes, FileType as FileType, SaveModes as SaveModes

logger: Incomplete

def get_output_path(is_animated: bool, input_path: Path, color_mode: ColorModes, output_arg: str | None = None, file_type: FileType = ...) -> tuple[Path, Path, Path | None, Path]: ...
def ensure_dir_exists(dir_path: str | Path) -> Path: ...
def create_temp_dir(base_dir: str | None = None, prefix: str = 'char_art_') -> Path: ...
def get_file_extension(file_path: Path) -> str: ...
def cleanup_files(*paths: str | Path) -> None: ...
def save_file(content: dict[str, Any], file_path: Path, description: str, save_mode: SaveModes, position: int = 0, should_stop: Callable[[], bool] | None = None) -> None: ...
from typing import List

# create_video_from_frames函数定义
def create_video_from_frames(frames: List[Any], output_path: Path, fps: float, codec: str = '', batch_index: int = 0, position: int = 0) -> None: ...

def execute_save_operation(save_params, should_stop=None, file_type=None): ...
def save_worker(save_params, interrupt_queue, result_queue): ...
def save_with_progress(save_params: dict, progress_func: Callable[[threading.Event, Callable[[], bool] | None], None], should_stop: Callable[[], bool] | None = None) -> None: ...
