from ..configs.message_config import WARNING_MESSAGES as WARNING_MESSAGES
from PIL import ImageFont
from _typeshed import Incomplete
from pathlib import Path

logger: Incomplete

class FontManager:
    logger: Incomplete
    def __init__(self) -> None: ...
    def get_system_fonts(self) -> list[Path]: ...
    def find_monospace_fonts(self) -> list[str]: ...
    def load_font(self, font_name: str, size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont: ...
    def get_best_monospace_font(self, size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont: ...
    def clear_cache(self) -> None: ...

def load_font(font_size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont: ...
def calculate_char_size(font) -> tuple[int, int]: ...
