from ..configs import DEFAULT_LOG_LEVEL as DEFAULT_LOG_LEVEL, LOG_DATE_FORMAT as LOG_DATE_FORMAT, LOG_FORMAT as LOG_FORMAT

def setup_logging(verbose: bool = False, log_level: str | None = None) -> None: ...
def get_current_log_config() -> dict: ...
