from ..configs import ALL_SUPPORTED_FORMATS as ALL_SUPPORTED_FORMATS, ERROR_MESSAGES as ERROR_MESSAGES
from .file_utils import get_file_extension as get_file_extension
from pathlib import Path
from typing import Any

def validate_input_file(file_path: Path) -> None: ...
def validate_output_path(output_path: Path) -> None: ...
def validate_arguments(args: Any) -> None: ...
