from _typeshed import Incomplete
from pathlib import Path
from typing import Optional, Callable

logger: Incomplete

def get_video_info(video_path: Path | str, show_format: bool = True, show_streams: bool = True, show_packets: bool = False, show_frames: bool = False) -> str: ...
def get_hw_decode_encode_config(output_path: Path) -> tuple[str, Optional[str]]: ...
def get_hw_decode_video_args(output_path: Path, encoder: Optional[str] = None) -> list[str]: ...
def create_video(frames_paths: list[Path], audio_path: Optional[Path], output_path: Path, temp_dir: Path, video_info: str, fps: float = 30.0, codec: Optional[str] = None, bitrate: int = 5000000, threads_num: int = 1, should_stop: Optional[Callable[[], bool]] = None) -> None: ...
